chore: up

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,12 +14,27 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@main
+
       - name: Install dependencies
         run: npm ci
+
+      - name: Check environment files
+        run: |
+          if [ ! -f src/environments/environment.ts ]; then
+            echo "src/environments/environment.ts not found"
+            exit 1
+          fi
+          if [ ! -f src/environments/environment.prod.ts ]; then
+            echo "src/environments/environment.prod.ts not found"
+            exit 1
+          fi
+
       - name: Build dependencies
         run: npm run build
+
       - name: Archive production artifact
         uses: actions/upload-artifact@main
+        
         with: 
           name: dist
           path: dist/historias-do-brasil/browser
