debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,17 +32,17 @@ jobs:
       - name: Display environment file content
         run: cat src/environments/environment.ts
         
-      - name: Check environment files
-        run: |
-          if [ ! -f src/environments/environment.ts ]; then
-            cd src/envionment
-            ls -al
-            exit 1
-          fi
-          if [ ! -f src/environments/environment.prod.ts ]; then
-            echo "src/environments/environment.prod.ts not found"
-            exit 1
-          fi
+      # - name: Check environment files
+      #   run: |
+      #     if [ ! -f src/environments/environment.ts ]; then
+      #       cd src/envionment
+      #       ls -al
+      #       exit 1
+      #     fi
+      #     if [ ! -f src/environments/environment.prod.ts ]; then
+      #       echo "src/environments/environment.prod.ts not found"
+      #       exit 1
+      #     fi
 
       - name: Build dependencies
         run: npm run build
